### PR TITLE
Feature/meeting type selection

### LINKED ISSUE #135: When creating a meeting, allow user to select meeting type (normal or 1v1)

### PR DESCRIPTION
**Pull request by Marsietis**
Added ability to select meeting type in add.blade.php

### CODE REVIEW

**Comment by nitrogency** [comment]
Nevermind. The issue was on my end. Everything works and feels great!

**Comment by Marsietis** [comment]
Can you aprove?

**Comment by nitrogency** [comment]
Actually just figured out it isn't a problem on my end. Thought it was a database error. Sorry for the confusion. Figured out that neither updating the 1v1 meeting or the simple meeting works anymore.

**Comment by Marsietis** [comment]
Oh yeah, the edit page is separate. Will fix soon

**Review by nitrogency — APPROVED** [review]
Got it, then approving. Good work!

**Pull request merged**
