### PR TITLE
Added an error message when timezone not selected.

### LINKED ISSUE #38: Does not give error on timezone selections
**Describe the bug**
When submitting a form for new meet creation, if the timezone field is empty when pressed submit- nothing happens, page just refreshes.

**To Reproduce**
1. Go to 'add-meeting'
2. Fill out all fields
3. Leave timezone field empty.
4. Submit the form.

**Expected behavior**
Throws and error, that the field cannot be empty.

### PR DESCRIPTION
**Pull request by nitrogency**

### CODE REVIEW

**Comment by nitrogency** [comment]
Should it be a custom error message or is "Timezone must be an integer" enough?

**Comment by Marsietis** [comment]
> Should it be a custom error message or is "Timezone must be an integer" enough?

Users are selecting timezone from a list, not entering a number, so the best message should be "Please select a timezone", or how in other fields it shows Please fill out this field

**Comment by nitrogency** [comment]
Got it, will change

**Review by Marsietis — APPROVED** [review]
Works great

**Pull request merged**
