### PR TITLE
Meeto sukūrimo formoje pridėti pagrindinę info#16

### LINKED ISSUE #16: Meeto sukūrimo formoje pridėti pagrindinę info
Reikia pridėti šiuos laukus:
- `description` (longText)
- `location` (string)
- `timezone` (string); kas apsiimsit šito, davai pakeiskit į `timezone_offset` (žr. `databases/migrations/2023_...`).
- `duration` (integer)
- `delete_after` (integer

### PR DESCRIPTION
**Pull request by nitrogency**
Ability to input description(textarea)
Ability to input location(string)
Ability to choose timezone(string)
Ability to input meeting duration(smallInteger)
Ability to input meeting deletion delay(integer)
"textarea.blade.php" component for the description 
Changes:
Changed 'timezone' to 'timezone_offset'

### CODE REVIEW

**Review by archlich03 — APPROVED** [review]
The code seems to be good. My recommendations:
- check the styling of the boxes
- rename the label `Duration` into something like `Duration (min)`
Otherwise all of the code is good

**Review by Marsietis — COMMENTED** [review]
Added a new commit to fix this, but the $valided was not doing anything, just validating, but the stored data was straight from request not from validated. Also now timezone selctor shows white text on white background

**Review by Marsietis — APPROVED** [review]
Look good now

**Review by archlich03 — CHANGES_REQUESTED** [review]
All previous concerns have been adressed, good job!

When testing the submission form, i noticed, that if there's an error, then the description gets wiped. That should be fixed, because it's the longest input that the user will need to do and if it gets cleared, it will be frustrating.

Here are the steps to recreate the issue that i'm talking about:
- open the form
- write anything in the description
- write a string in the duration part (should be integer)
- finish filling out form normally
- submit

**Review by archlich03 — APPROVED** [review]
Works well, my adressed issue has been solved. Good job!

**Pull request merged**
