### PR TITLE
Feature/add-an-option-to-finalize-a-meeting time

### LINKED ISSUE #164: Add an option to finalize a meeting time
it should appear on the meeting page as selected

### PR DESCRIPTION
**Pull request by nitrogency**
Added an option in the dropdown menu to finalize a date. This saves the value to the database. Only one date may be selected per meeting. If another one was already selected, it no longer becomes selected, instead assigning it to the newly selected date. This is to prevent the meeting creator from accidentally selecting the wrong date and having to re-do the meeting.

I changed the following:

- In `app/Models/Date.php` I added the 'selected' attribute to each date. I updated the migrations table accordingly, assigning it the type of 'tinyInteger'. Didn't use booleans because MySQL apparently doesn't like them.

- In `app/Http/Controllers/DateController.php`, I edited the "update" function. Previously it was used for updating dates, but since that functionality isn't used anymore, I repurposed it for updating the date's "selected" attribute to the database instead. Previously I used a `select` function for this, but I figured using an already existing function would be more efficient.

- In `app/Http/Requests/StoreDate.php` I changed the `rules` function. Now the rules regarding the date numbers and uniqueness only apply when a new date is being created. This prevents unnecessary checks from back when you could edit dates. Now these rules apply only when adding a date. 

- In `resources/views/meetings/meeting-cards.blade.php` I changed the forms to allow the "Finalize" button to work, while retaining previous functionality. I also added JavaScript at the end, which is responsible for checking whether a date is selected and assigning a badge indicating so. This script is quite large and situational, so I figured keeping it here may be a better choice than loading it each time in `app.js`.

- Finally, removed a route I had previously added, since it was no longer necessary due to the `select` function no longer existing.

### CODE REVIEW

**Review by Marsietis — CHANGES_REQUESTED** [review]
Having hard time reviewing, as this was made before the refactoring, where functions to edit dates were removed and 1 on 1 meetings were added. Now it breaks too many things, like 1 on 1 meetings don't work, in meeting page votes are displayed two times. Could you please do this functionality on current main branch. As I can see all that needs to be re-done for that is migration, a badge in the view and a function in DateController.

**Comment by Marsietis** [comment]
Also maybe a separate button next to add times for finalizing times that calls a popup with time selection (and explanation for finalizing time) would be better.

**Comment by nitrogency** [comment]
Got it, will change accordingly

**Comment by nitrogency** [comment]
Going to make a new PR and branch due to just how many things are different.

**Pull request closed without merging**
