### PR TITLE
Feature/store votes

### LINKED ISSUE #79: Create the option to store votes

### PR DESCRIPTION
**Pull request by Marsietis**
Documentation  in commits.

### CODE REVIEW

**Review by nitrogency — APPROVED** [review]
Works well, looks good too. The note about names being shown is a nice touch. I do think votes should start as de-selected, so a person selects those he wants rather than those he doesn't. 

Also, I'm not sure if there's supposed to be a "saved successfully" message? It's seen in the code, but I can't see it anywhere when voting in the actual page.

**Review by archlich03 — COMMENTED** [review]
The backend is really clean, the functionality seems good. Here are a couple of general observations:
- maybe there should be a close/cancel button in the voting box? If you press the "vote on times" button, you can't close out without submitting the form.
- imo when voting the checkboxes should probably be unchecked.
- maybe it would've been better to integrate the voting checkboxes in the current date cards?

**Comment by nitrogency** [comment]
There is a way to exit, by hitting escape, but true, I also think there should be a cancel button somewhere

**Comment by Marsietis** [comment]
Right. Will post changes according to feedback soon.

**Comment by Marsietis** [comment]
Yes the exit button used to be the submit button until i changed it. Will ad like an x or something.

**Comment by Marsietis** [comment]
> maybe it would've been better to integrate the voting checkboxes in the current date cards?

There was two options. This or have a namebox and submit votes button somewhere visible. Decided to go with this as it is cleaner and users will probably vote only once, and after that we will be able to hide the button for voting.

**Comment by Marsietis** [comment]
Made requested changes and more. Feedback would be appreciated.

**Review by archlich03 — APPROVED** [review]
All good now. One nitpick i can think of is that the dates are sorted from newest to oldest. I think it'd better if it were the other way around. I think you can merge this PR

**Comment by nitrogency** [comment]
Everything looks good now, well done!

**Review by nitrogency — APPROVED** [review]

**Pull request merged**
