### PR TITLE
Feature/add-option-so-only-the-meeting-maker-can-see-the-votes-results

### PR DESCRIPTION
**Pull request by nitrogency**
## Description

Added an advanced options section to the add and edit meeting pages. Added an option to make votes invisible to everyone except the meeting creator.

## Changes Made

-  Added a clickable text in `resources/views/meetings/add.blade.php` and `resources/views/meetings/edit.blade.php`. When pressed, it shows the advanced options the user may select. Currently there's one checkbox, where the user may select the votes to be invisible to everyone except themselves.
- Added checks in `resources/views/meetings/meeting-cards.blade.php`, which are necessary to hide information if `voter_invisible` is equal to 1.
-  In `app/Http/Controllers/MeetingController.php` added a validation check for the voter_invisible variable. For some reason, doing it the usual way doesn't work, as the validated variable isn't being passed for whatever reason. I checked the meeting model, validation file, and migrations table, yet it still didn't work regularly. That's why there's a workaround, where it first checks if the variable exists at all. If it doesn't, then it assigns 0 and moves on.
- In `app/Http/Requests/StoreMeeting.php` added validation for the `voter_invisible` variable.
- In `app/Models/Meeting.php` added the `voter_invisible` variable. `is1v1` was missing, so I added it too.
- Changed database migrations to accomodate the new `voter_invisible` variable. Default value is zero.
- Changed `tests/Feature/MeetingTest.php` to include the new variable.
- Added localization.

## Related Issues

Add option so only the meeting maker can see the vote results #234 

## Checklist

- [x] Code works without errors or warnings
- [x] I have performed a self-review of my code
- [x] Coding style and guidelines have been followed

### CODE REVIEW

**Comment by nitrogency** [comment]
Don't merge, found a bug

**Comment by nitrogency** [comment]
Should be good now.

**Review by Marsietis — APPROVED** [review]
Works good, looks good, only problem, when editing meeting, the value is not selected, even if when creating it was selected

**Comment by nitrogency** [comment]
Got it, will fix

**Pull request merged**
