### PR TITLE
Add success notification for meeting creation

### LINKED ISSUE #59: Add a notification to show when meeting added successfully

### PR DESCRIPTION
**Pull request by Marsietis**
This commit adds a success notification that is displayed to the user when a meeting is created successfully. This involves a change in the MeetingController to return a success message along with the redirect to the dashboard. A new notification component has been added to the views as well, which shows the success message and automatically fades out after 2 seconds. This component has been included in the dashboard view, making it only visible when a success session variable exists. The aim is to give users clear feedback when a meeting is successfully created.

### CODE REVIEW

**Review by nitrogency — APPROVED** [review]
Well done, both with the description and code itself

**Review by archlich03 — CHANGES_REQUESTED** [review]
The core of the implementation looks good: once the user is redirected to the page, it shows the message. Though if they visit another page (for example look at a meeting) and go back with in the browser, the message appears again. this might be confusing for the user. A fix should be implemented, so that the message shows only once per added meeting

**Comment by Marsietis** [comment]
Read this:
The nature of the web browser's back and forward buttons sometimes make the pages not initiate a new request to the server and hence "flashed" session data might be available again which were meant to only live for the next request. This can be seen as a kind of caching made by the browser to quickly navigate between already visited pages.
You have used JavaScript to fade out the alert box but when you come back with the "back button", the faded out box appears again because it is how the browser's cache works which is beyond the control of Laravel's server session.
One way to address this issue though is to tell the browser not to cache the page.|
Can't decide what to do. We can add code not not cache dashboard(although minimal but still a performance impact). Or maybe add a back button to tasks that will make request to dashboard. Ideas?

**Comment by Marsietis** [comment]
> Read this: The nature of the web browser's back and forward buttons sometimes make the pages not initiate a new request to the server and hence "flashed" session data might be available again which were meant to only live for the next request. This can be seen as a kind of caching made by the browser to quickly navigate between already visited pages. You have used JavaScript to fade out the alert box but when you come back with the "back button", the faded out box appears again because it is how the browser's cache works which is beyond the control of Laravel's server session. One way to address this issue though is to tell the browser not to cache the page.| Can't decide what to do. We can add code not not cache dashboard(although minimal but still a performance impact). Or maybe add a back button to tasks that will make request to dashboard. Ideas?

Also no cache solution does not appear to be working

**Comment by archlich03** [comment]
Lets leave it as it is, then. Playing with caching now doesn't seem like a good idea with such a small thing.

**Review by archlich03 — APPROVED** [review]

**Pull request merged**
