### PR TITLE
Added a check to allow auth'ed users to vote on meetings

### LINKED ISSUE #171: Voting doesn't work when logged in
**Describe the bug**
Cannot vote on a date if you are logged in into your account.

**To Reproduce**
1. Login into your account.
2. Click on someone's (not your own) meeting link.
3. The "vote for a date" button doesn't appear.

**Expected behavior**
The voting button should still appear when logged in.

**Screenshots**
Meeting when not logged in:

image

Meeting when logged in:

image

### PR DESCRIPTION
**Pull request by archlich03**
No functions changed. very complex code

### CODE REVIEW

**Review by Marsietis — CHANGES_REQUESTED** [review]
Bad

**Comment by archlich03** [comment]
> Bad

no

**Review by Marsietis — APPROVED** [review]
LGTM

**Review by nitrogency — APPROVED** [review]
"Perfectly balanced, as all things should be:"

image

**Pull request merged**
